arm_joint_1_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint_1
  pid: {p: 10.0, d: 2.0}
arm_joint_2_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint_2
  pid: {p: 10.0, d: 2.0}
arm_joint_3_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint_3
  pid: {p: 10.0, d: 2.0}
arm_joint_4_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint_4
  pid: {p: 10.0, d: 2.0}
arm_joint_5_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint_5
  pid: {p: 10.0, d: 2.0}
gripper_finger_joint_l_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper_finger_joint_l
  pid: {p: 10.0, d: 2.0}
gripper_finger_joint_r_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper_finger_joint_r
  pid: {p: 10.0, d: 2.0}
